# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'YouRun!' do
  use_frameworks!

  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'YouRun!Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
